slack:
  token: "your token"
  error_channel: ""
  dev_panel_url: ""
oss:
  domain: hymn.tv

stripe:
  key: "api_key"
  webhook_secrets:
    checkout: "key"

checkout:
  secret_key: "secret_key"
  public_key: "public_key"
  currency: "GBP"
  webhook_keys:
    main: "some_key"

amazon_s3:
  endpoint: "https://somestorage.com"
  access_key_id: ""
  secret_access_key: ""
  disable_ssl: false
  region: us-east-1
  url_prefix: prefix
  domain: domain.com
  buckets:
    product:
      prod: bucket-name
      local: bucket-name-local
orm_debug: true