slack:
  error_channel: ""
  dev_panel_url: ""
  bot_tokens:
    errors: "your token"

stripe:
  key: "api_key"
  webhook_secrets:
    checkout: "key"

checkout:
  secret_key: "secret_key"
  public_key: "public_key"
  currency: "GBP"
  webhook_keys:
    main: "some_key"

oss:
  amazon:
    endpoint: "https://somestorage.com"
    access_key_id: ""
    secret_access_key: ""
    disable_ssl: false
    region: us-east-1
  buckets:
    some-bucket:
      prod:
        name: bucket-name
        cdn_url: "https://example.com/{Env}/{Bucket}/{StorageKey}"
      local:
        name: bucket-name-local
        cdn_url: "http://127.0.0.1/{Env}/{Bucket}/{StorageKey}"
orm_debug: false
