# https://docs.codecov.io/docs/commit-status
coverage:
    range: 0..50
    round: down
    precision: 0
    status:
      project:
        default:
          target: 15%
          threshold: 0%
      patch:
        default:
          target: 15%
          threshold: 0%