orm:
  default:
    mysql: root:root@tcp(host.docker.internal:9004)/hitrix
    redis: host.docker.internal:9002:1
    locker: default
    local_cache: 1000
cors:
  - http://localhost:9001 # This is the default port of https://github.com/coretrix/dev-frontend repository
