orm:
  default:
    mysql: ENV[DEFAULT_MYSQL]
    redis: ENV[DEFAULT_REDIS]
    locker: default
    local_cache: 1000
  search:
    redis: ENV[DEFAULT_REDIS_SEARCH]
cors:
  - http://localhost:9001 # This is the default port of https://github.com/coretrix/dev-frontend repository
  - http://localhost:63342 # websocket test
