name: Check & test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Quality & security checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE hitrix;' -uroot -proot

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint Go Code
        run: |
          export GOPATH=$(go env GOPATH)
          go mod tidy
          make check

  test:
    name: Test & coverage
    runs-on: ubuntu-latest
    services:
      redis:
        image: redislabs/redisearch
        ports:
          - 9002:6379

    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run unit tests with coverage.
        run: |
          export GOPATH=$(go env GOPATH)
          go mod tidy
          make cover

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.2.2
        with:
          file: ./resources/cover/cover.out
