name: Hitrix

on: push

jobs:
  checks:
    name: Quality & Security checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint code
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make check

  tests:
    name: Tests with coverage
    runs-on: ubuntu-latest
    needs: checks
    services:
      redis:
        image: redislabs/redisearch:latest
        ports:
          - 9002:6379
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure MySQL & Create databases
        run: |
          sudo bash -c 'echo -e "[mysqld]\nport=9004\n" >> /etc/mysql/my.cnf'
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE hitrix;' -uroot -proot

      - name: Run tests
        run: |
          export GOPATH=$(go env GOPATH)
          make cover

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.2.2
        with:
          file: ./resources/cover/cover.out
